"""add enablebanking account uid to accounts

Revision ID: a899dc5a41d9
Revises: ca0bffa928db
Create Date: 2026-08-08 13:20:13.187144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a899dc5a41d9'
down_revision: Union[str, Sequence[str], None] = 'ca0bffa928db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('enablebanking_account_uid', sa.String(), nullable=False))
    op.create_unique_constraint('uq_accounts_enablebanking_account_uid', 'accounts', ['enablebanking_account_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accounts_enablebanking_account_uid', 'accounts', type_='unique')
    op.drop_column('accounts', 'enablebanking_account_uid')
    # ### end Alembic commands ###
