import os

from dotenv import load_dotenv

load_dotenv()

ENABLE_BANKING_APPLICATION_ID = os.environ["ENABLE_BANKING_APPLICATION_ID"]
ENABLE_BANKING_PRIVATE_KEY_PATH = os.environ["ENABLE_BANKING_PRIVATE_KEY_PATH"]
ENABLE_BANKING_REDIRECT_URL = os.environ["ENABLE_BANKING_REDIRECT_URL"]
